eureka:
  client:
    serviceUrl:
      defaultZone : http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
    healthcheck:
      enabled: true
    instance:
      lease-expiration-duration-in-seconds: 5
      lease-renewal-interval-in-seconds: 10
feign:
  hystrix:
    enabled: true
server:
  port: 7899
spring:
  application:
    name : MainFeignClient